@Menager_floty_HostAddress = http://localhost:8080

POST {{Menager_floty_HostAddress}}/api/users/login
Content-Type: application/json

{
  "email": "kb@kb.pl",
  "password": "qwerty123"
}

###

GET {{Menager_floty_HostAddress}}/api/Trailer/refrigeratorInspections/trailer/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoia2JAa2IucGwiLCJleHAiOjE3NzgwMDQwNDIsImlzcyI6IkJhY2tlbmQiLCJhdWQiOiJGcm9udGVuZCJ9.gP6FW6wE71T8dIpmMIjW7PxSf8F9YHs0FvrhjKdchSk

###

DELETE {{Menager_floty_HostAddress}}/api/Cars/3

###
